### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by jhzhang2077** [buildingnet/buildingnet_dataset#1]
I'm using nvidia3090 with cuda11.3. The OOM error happens with building 50 or 300. I don't konw whether it relies on the software or hardware environment.
May I konw the hardware requirments? Thanks!

**Comment by buildingnet** [comment]
Hi,

Regarding the GNN training, the 2080Ti was used (memory size 11GB).

**Comment by amiltonwong** [comment]
I have the same issue as @jhzhang2077 (also using RTX 3090 GPU). The error shows `run out of GPU memory`, [details](https://gist.github.com/amiltonwong/ab865ae630763bcccc0e101680ce7bb0). But it's strange as RTX 3090 GPU provides 24GB GPU, while you mentioned that you just used a lower memory GPU (2080Ti).
