### ISSUE TITLE
The part label name map

### ISSUE THREAD

**Issue by SunWeiLin-Lynne** [buildingnet/buildingnet_dataset#10]
Hi, authors
Could you provide the label name map for the part label ID in Building Net_dataset_v1?
Thanks.

**Comment by buildingnet** [comment]
Hi. A full list of the part labels that are included in BuildingNet v1 can be found [here](https://drive.google.com/file/d/1ZpvvyF9oR1vBQPwknFCVnV02tgFH6vyN/view?usp=share_link). (```label_id: label_name```)

**Comment by amiltonwong** [comment]
@buildingnet, could you also provide the color map for the part labels? It'll be useful for visualization.

**Comment by buildingnet** [comment]
You can use this [color map](https://github.com/buildingnet/buildingnet_dataset/blob/6e97ca48f584530fc325c8d0708456b1f0870767/MinkowskiNet/lib/datasets/buildingnet.py#L22-L55) (```label_id: (R, G, B)```) for the part labels visualization.
