### ISSUE TITLE
The  face IDs for each object

### ISSUE THREAD

**Issue by SunWeiLin-Lynne** [buildingnet/buildingnet_dataset#11]
Hello, thank you very much for your work.
According to my understanding of Building Net_dataset_v1, each object, such as a window, wall, roof, is made up of multiple components. The face IDs for each component are provided in the dataset. Does the dataset provide face IDs for each object?

**Comment by buildingnet** [comment]
Yes each object is composed of multiple components and the face IDs that are provided, correspond to these components and not the entire object. Currently we do not provide the face IDs for the whole object.

**Comment by SunWeiLin-Lynne** [comment]
Thanks.
