### ISSUE TITLE
Model verification error: `FileNotFoundError: [Errno 2] No such file or directory: 'data/pretrained_avgpool_minkownormal_features/fc3_avg/RESIDENTIALhouse_mesh1367.pth.tar'`

### ISSUE THREAD

**Issue by ozanyetkin** [buildingnet/buildingnet_dataset#16]
Hello and thank you for sharing your great work!

I have faced an issue about the following:

## Problem
When the BuildingNet dataset is downloaded by filling out the [form](https://docs.google.com/forms/d/e/1FAIpQLSevg7fWWMYYMd1vaOdDloUX_55VOQK7PqS1DlniFV7_vuoI0w/viewform), there are several versions available, yet it seems like some models are missing in `pretrained_avgpool_minkownormal_features`.

### Example
Running the following code as [BuildingNet repository](https://github.com/buildingnet/buildingnet_dataset) suggests:

```
python3 train.py --datadir="data" --epoch 200 --outputdir 'Output' --ckpt_dir 'checkpoint' --normalization 'GN' --modeltype 'Edge' --edgetype 'all' --lr 1e-4 --nodetype 'node+minkownormal' --pretrainedtype 'fc3_avg' --IOU_checkpoint=5
```

Throws the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'data/pretrained_avgpool_minkownormal_features/fc3_avg/RESIDENTIALhouse_mesh1367.pth.tar'
```

Yet, I have resolved it with a simple script and shared it via [this repository.](https://github.com/ozanyetkin/buildingnet-model-verifier)

In case anyone faces the same issue, feel free to use it!

**Comment by buildingnet** [comment]
Presently, only BuildingNet v0 offers pretrained MinkNet features, which have been trained on the entirety of BuildingNet v0, covering 2,000 building models. For BuildingNet v1, which comprises a subset of v0 containing a total of 1,849 building models, you can access the pretrained MinkNet features (trained specifically on BuildingNet v1) by following the instructions outlined in [this guide](https://github.com/buildingnet/buildingnet_dataset/tree/main/MinkowskiNet#export-features-for-buildinggnn).

**Comment by ozanyetkin** [comment]
Great, thanks! I will try to extend the dataset for my ongoing research. I will probably share the updates from my [forked version](https://github.com/ozanyetkin/buildingnet-dataset) of BuildingNet.
