### ISSUE TITLE
BuildingNet-Mesh

### ISSUE THREAD

**Issue by weiyao1996** [buildingnet/buildingnet_dataset#2]
Dear authors,

Thanks for your work. 
Have you provided the data for BuildingNet-Mesh?
Could you please introduce how to extract the mesh file from the given datasets? I would like to access the 3D mesh model for each building.

Best,

**Comment by buildingnet** [comment]
Hi,

Thanks for showing interest in our work. You can download the BuildingNet dataset by filling this [form](https://forms.gle/jFQpoRzRkrTCaTzX8). For each building, we provide its 3D mesh in OBJ format (see OBJ_MODELS.zip in the Google Drive folder). You can also find some extra information regarding the 3D meshes, e.g., face labels or component labels, under the folder `mode_data/obj`.
