### ISSUE TITLE
question about the 41D node representation

### ISSUE THREAD

**Issue by amiltonwong** [buildingnet/buildingnet_dataset#4]
Hi, authors,

According to the original paper, the representation for each node (subgroup) is 41-dim, which corresponds to four kinds of spatial features, such as: i) initial node representation, ii) 3D barycenter position of subgroup, iii) mesh surface area, iv) coordinates of the opposite corners of OBB. Could you elaborate on the specific feature dimensions related to the above four kinds of spatial features? e.g. how many dimensions does the initial node representation contain?

Thanks~

**Comment by buildingnet** [comment]
Hi.

The initial node representation is formed by extracting the per-point features from the last layer (31D) of a network that is trained on the BuildingNet point clouds (MinkNet or PointNet in our case). Then average pooling is performed over the points originating from the faces of the subgroup to extract an initial node representation. The 3D barycenter position of a subgroup is a 3D feature. The same holds for the coordinates of the opposite corners of each OBB (3D coordinates for each corner). Finally, the mesh surface area is represented by a scalar value. Concatenating these into one feature representation of a subgroup, a 41D vector is formed representing each node of the graph.
