### ISSUE TITLE
how to visualize the component for the building mesh file

### ISSUE THREAD

**Issue by amiltonwong** [buildingnet/buildingnet_dataset#5]
Hi, authors,

How could we visualize the component for the building mesh file? Is there any faces list provided for each component?

Thanks

**Comment by buildingnet** [comment]
Hi.

Along with the OBJ files of the building models, we also provide the `faceindex_componentID.zip` (under `/model_data/obj`), where the face indices of the components of each model are stored in separate .json files (one for each OBJ). The mapping of face indices to component ids is stored in the following format:
```
	“start_face_idx”:
		{ “end_face_idx”: “component_id”}
```

,i.e., the faces with indices `[start_face_idx:end_face_idx]` belong to the component with the specified id.
