### ISSUE TITLE
the color map for part labels

### ISSUE THREAD

**Issue by amiltonwong** [buildingnet/buildingnet_dataset#7]
Hi, authors,

For the usage of visualization, could you provide the color map for those 31 part labels (as mentioned in Table 7 in the original paper)?

Thanks~

**Comment by prathebaselva** [comment]
Hi,
These are the color codes
COLORS ={"moat_ditch":"#ffaa1d","shutters":"#0dd3ff","awning":"#ffbbdd","door":"#7f0000","wall":"#ff4500", "window":"#0000ff", "roof":"#4b008c", "ceiling":"#ff00ff", "floor":"#400000","chimney":"#999673", "stairs":"#60b9bf", "balcony_patio":"#301040", "beam_frame":"#ff4040", "column":"#3d4010", "entrance_gate":"#00aaff", "lantern_lamp":"#cc00ff", "garage":"#ff9180", "canopy_gazebo":"#c3e639", "gazebo":"#396073", "parapet":"#8a4d99","parapet_merlon":"#8a4d99","dormer": "#8c6e69", "tower_steeple":"#d6f2b6", "furniture":"#0d2133", "entablature":"#d936b8", "arch":"#b24700", "pediment":"#0f7300", "crepidoma":"#bfe1ff", "dome":"#997391", "tympanum":"#e5a173", "buttress":"#40ff73", "merlon":"#3662d9", "bridge":"#660036", "ground":"#9370db", "ramp":"#00401a", "fence":"#394173", "corridor_path":"#bf3069", "railing_baluster":"#733d00", "plant_tree":"#fa8072", "pond_pool":"#553df2", "road":"#ffbfd9", "seats_deck":"#ffaa00", "ground_grass":"#204035", "vehicle":"#396073","cannot_label":"#696969"}
